// Funcionalidades para a página de legislação tributária
document.addEventListener('DOMContentLoaded', function() {
    // Navegação suave para as seções
        document.querySelectorAll('.nav-link').forEach(link => {
                link.addEventListener('click', function(e) {
                            e.preventDefault();
                                        const targetId = this.getAttribute('href');
                                                    document.querySelector(targetId).scrollIntoView({
                                                                    behavior: 'smooth'
                                                                                });
                                                                                        });
                                                                                            });

                                                                                                // Tabs da calculadora
                                                                                                    const calcTabs = document.querySelectorAll('.calc-tab');
                                                                                                        const calcContents = document.querySelectorAll('.calc-content');

                                                                                                            calcTabs.forEach(tab => {
                                                                                                                    tab.addEventListener('click', function() {
                                                                                                                                const tabId = this.getAttribute('data-tab');
                                                                                                                                            
                                                                                                                                                        // Remover classe active de todas as tabs
                                                                                                                                                                    calcTabs.forEach(t => t.classList.remove('active'));
                                                                                                                                                                                calcContents.forEach(c => c.classList.remove('active'));
                                                                                                                                                                                            
                                                                                                                                                                                                        // Adicionar classe active à tab clicada
                                                                                                                                                                                                                    this.classList.add('active');
                                                                                                                                                                                                                                document.getElementById(`${tabId}-calc`).classList.add('active');
                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                // Calculadora do Simples Nacional
                                                                                                                                                                                                                                                    const calcularSimplesBtn = document.getElementById('calcularSimples');
                                                                                                                                                                                                                                                        if (calcularSimplesBtn) {
                                                                                                                                                                                                                                                                calcularSimplesBtn.addEventListener('click', calcularSimples);
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                    function calcularSimples() {
                                                                                                                                                                                                                                                                        const faturamento = parseFloat(document.getElementById('faturamento').value) || 0;
                                                                                                                                                                                                                                                                            const anexo = parseInt(document.getElementById('anexo').value);
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    if (faturamento <= 0) {
                                                                                                                                                                                                                                                                                            alert('Por favor, insira um valor válido para o faturamento.');
                                                                                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                if (faturamento > 4800000) {
                                                                                                                                                                                                                                                                                                                        document.getElementById('resultadoSimples').innerHTML = 
                                                                                                                                                                                                                                                                                                                                    '<span style="color: var(--error);">Empresa não se enquadra no Simples Nacional (faturamento acima de R$ 4.800.000,00)</span>';
                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        const mensal = faturamento / 12;
                                                                                                                                                                                                                                                                                                                                                            let aliquota, deducao;
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                    // Tabelas do Simples Nacional 2023 (valores ilustrativos)
                                                                                                                                                                                                                                                                                                                                                                        switch(anexo) {
                                                                                                                                                                                                                                                                                                                                                                                case 1: // Anexo I - Comércio
                                                                                                                                                                                                                                                                                                                                                                                            if (mensal <= 18000) { aliquota = 0.04; deducao = 0; }
                                                                                                                                                                                                                                                                                                                                                                                                        else if (mensal <= 60000) { aliquota = 0.073; deducao = 594; }
                                                                                                                                                                                                                                                                                                                                                                                                                    else if (mensal <= 120000) { aliquota = 0.095; deducao = 1386; }
                                                                                                                                                                                                                                                                                                                                                                                                                                else if (mensal <= 240000) { aliquota = 0.107; deducao = 2250; }
                                                                                                                                                                                                                                                                                                                                                                                                                                            else { aliquota = 0.143; deducao = 8730; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 2: // Anexo II - Indústria
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (mensal <= 18000) { aliquota = 0.045; deducao = 0; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if (mensal <= 60000) { aliquota = 0.078; deducao = 594; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (mensal <= 120000) { aliquota = 0.10; deducao = 1386; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else if (mensal <= 240000) { aliquota = 0.112; deducao = 2250; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else { aliquota = 0.147; deducao = 8550; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 3: // Anexo III - Serviços
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (mensal <= 18000) { aliquota = 0.06; deducao = 0; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if (mensal <= 60000) { aliquota = 0.112; deducao = 936; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (mensal <= 120000) { aliquota = 0.135; deducao = 1764; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else if (mensal <= 240000) { aliquota = 0.16; deducao = 3564; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else { aliquota = 0.21; deducao = 12564; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            aliquota = 0.15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        deducao = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const impostoMensal = (mensal * aliquota) - deducao;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const impostoAnual = impostoMensal * 12;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const aliquotaEfetiva = (impostoAnual / faturamento) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('resultadoSimples').innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Imposto Mensal:</strong> ${formatCurrency(impostoMensal)}<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>Imposto Anual:</strong> ${formatCurrency(impostoAnual)}<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>Alíquota Efetiva:</strong> ${aliquotaEfetiva.toFixed(2)}%<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>Faturamento Líquido:</strong> ${formatCurrency(faturamento - impostoAnual)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function formatCurrency(value) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Intl.NumberFormat('pt-BR', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: 'currency',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currency: 'BRL'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }).format(value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Funções para outras calculadoras (seriam implementadas)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function calcularIRPJ() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Implementação para cálculo de IRPJ/CSLL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function calcularICMS() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Implementação para cálculo de ICMS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }