// Cálculos para a planilha de projeção
document.addEventListener('DOMContentLoaded', function() {
    const calculateBtn = document.getElementById('calculateProjection');
        const exportBtn = document.getElementById('exportData');
            
                calculateBtn.addEventListener('click', calculateProjection);
                    exportBtn.addEventListener('click', exportToExcel);
                        
                            // Calcular automaticamente ao carregar a página
                                calculateProjection();
                                });

                                function calculateProjection() {
                                    // Obter valores dos inputs
                                        const initialInvestment = parseFloat(document.getElementById('investmentValue').value) || 0;
                                            const monthlyInvestment = parseFloat(document.getElementById('monthlyInvestment').value) || 0;
                                                const annualInterest = parseFloat(document.getElementById('annualInterest').value) || 0;
                                                    const years = parseInt(document.getElementById('investmentPeriod').value) || 0;
                                                        
                                                            // Validar entradas
                                                                if (annualInterest < 0 || years <= 0) {
                                                                        alert('Por favor, insira valores válidos para taxa de juros e período.');
                                                                                return;
                                                                                    }
                                                                                        
                                                                                            // Calcular valores
                                                                                                const monthlyRate = annualInterest / 100 / 12;
                                                                                                    const months = years * 12;
                                                                                                        
                                                                                                            let currentBalance = initialInvestment;
                                                                                                                let totalInvested = initialInvestment;
                                                                                                                    let totalInterest = 0;
                                                                                                                        
                                                                                                                            const tableBody = document.getElementById('projectionTableBody');
                                                                                                                                tableBody.innerHTML = '';
                                                                                                                                    
                                                                                                                                        // Calcular ano a ano
                                                                                                                                            for (let year = 1; year <= years; year++) {
                                                                                                                                                    let yearlyInterest = 0;
                                                                                                                                                            const startingBalance = currentBalance;
                                                                                                                                                                    
                                                                                                                                                                            // Calcular mês a mês para cada ano
                                                                                                                                                                                    for (let month = 1; month <= 12; month++) {
                                                                                                                                                                                                const monthlyInterest = currentBalance * monthlyRate;
                                                                                                                                                                                                            yearlyInterest += monthlyInterest;
                                                                                                                                                                                                                        currentBalance += monthlyInterest + monthlyInvestment;
                                                                                                                                                                                                                                    totalInvested += monthlyInvestment;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            totalInterest += yearlyInterest;
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            // Adicionar linha na tabela
                                                                                                                                                                                                                                                                                    const row = document.createElement('tr');
                                                                                                                                                                                                                                                                                            row.innerHTML = `
                                                                                                                                                                                                                                                                                                        <td>${year}</td>
                                                                                                                                                                                                                                                                                                                    <td>${formatCurrency(startingBalance)}</td>
                                                                                                                                                                                                                                                                                                                                <td>${formatCurrency(monthlyInvestment * 12)}</td>
                                                                                                                                                                                                                                                                                                                                            <td>${formatCurrency(yearlyInterest)}</td>
                                                                                                                                                                                                                                                                                                                                                        <td>${formatCurrency(currentBalance)}</td>
                                                                                                                                                                                                                                                                                                                                                                `;
                                                                                                                                                                                                                                                                                                                                                                        tableBody.appendChild(row);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    // Atualizar resumo
                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('totalInvestedValue').textContent = formatCurrency(totalInvested);
                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('totalInterestValue').textContent = formatCurrency(totalInterest);
                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('finalValue').textContent = formatCurrency(currentBalance);
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        const profitability = ((currentBalance - totalInvested) / totalInvested) * 100;
                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('profitabilityValue').textContent = `${profitability.toFixed(2)}%`;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            function formatCurrency(value) {
                                                                                                                                                                                                                                                                                                                                                                                                                return new Intl.NumberFormat('pt-BR', {
                                                                                                                                                                                                                                                                                                                                                                                                                        style: 'currency',
                                                                                                                                                                                                                                                                                                                                                                                                                                currency: 'BRL'
                                                                                                                                                                                                                                                                                                                                                                                                                                    }).format(value);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    function exportToExcel() {
                                                                                                                                                                                                                                                                                                                                                                                                                                        // Simular exportação para Excel
                                                                                                                                                                                                                                                                                                                                                                                                                                            alert('Funcionalidade de exportação para Excel será implementada em breve!\n\nOs dados da tabela serão convertidos para formato XLSX e disponibilizados para download.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Em uma implementação real, aqui usariamos uma biblioteca como SheetJS
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Para criar um arquivo Excel verdadeiro a partir dos dados da tabela
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }